<?php

/*
|--------------------------------------------------------------------------
| AKH Solutions - Design Theme Presets
|--------------------------------------------------------------------------
|
| Each theme is a complete, swappable "design" for the public site. The admin
| can activate any of these and override individual tokens. Tokens are emitted
| as CSS custom properties (--ak-*) onto the site root, so every public
| component is theme-agnostic and re-skins instantly.
|
| Keys:
|   hero_variant  - which hero component renders (aurora|quantum|nova|vertex|pulse|minimal|flux)
|   layout_variant- structural tweaks for nav/sections (standard|split|editorial|systems)
|   uses_three    - loads the Three.js WebGL background for that hero
|
*/

return [

    'aurora' => [
        'name' => 'Aurora',
        'description' => 'Dark, Superhuman-grade craft. Cyan→blue→purple gradient, glassmorphism, floating UI. The flagship AKH look.',
        'hero_variant' => 'aurora',
        'layout_variant' => 'standard',
        'uses_three' => false,
        'is_premium' => false,
        'tokens' => [
            'bg' => '#07080d',
            'bg2' => '#0b0d14',
            'surface' => '#10131c',
            'surface2' => '#161a26',
            'glass' => 'rgba(22,26,38,0.55)',
            'glassBorder' => 'rgba(255,255,255,0.08)',
            'hairline' => 'rgba(255,255,255,0.07)',
            'text' => '#f3f5fb',
            'textSecondary' => '#aab2c5',
            'textMuted' => '#727a8e',
            'primary' => '#5778f8',
            'primaryHover' => '#6f8bff',
            'onPrimary' => '#ffffff',
            'gradFrom' => '#28baf3',
            'gradVia' => '#5778f8',
            'gradTo' => '#7e2cfd',
            'ring' => 'rgba(87,120,248,0.55)',
            'glow' => 'rgba(87,120,248,0.35)',
            'fontDisplay' => "'Space Grotesk'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '16px',
            'navBg' => 'rgba(7,8,13,0.72)',
            'footerBg' => '#05060a',
            'scheme' => 'dark',
        ],
    ],

    'quantum' => [
        'name' => 'Quantum',
        'description' => 'Deep-space AI lab. Live Three.js neural particle field, neon cyan & violet, mono accents. Mind-blowing first paint.',
        'hero_variant' => 'quantum',
        'layout_variant' => 'standard',
        'uses_three' => true,
        'is_premium' => true,
        'tokens' => [
            'bg' => '#04050a',
            'bg2' => '#070912',
            'surface' => '#0a0d1a',
            'surface2' => '#101424',
            'glass' => 'rgba(12,16,30,0.5)',
            'glassBorder' => 'rgba(99,179,255,0.16)',
            'hairline' => 'rgba(120,160,255,0.1)',
            'text' => '#eaf2ff',
            'textSecondary' => '#9fb2d8',
            'textMuted' => '#69708a',
            'primary' => '#36e2ff',
            'primaryHover' => '#67ecff',
            'onPrimary' => '#03060f',
            'gradFrom' => '#22d3ee',
            'gradVia' => '#6366f1',
            'gradTo' => '#a855f7',
            'ring' => 'rgba(54,226,255,0.5)',
            'glow' => 'rgba(54,226,255,0.4)',
            'fontDisplay' => "'Space Grotesk'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '14px',
            'navBg' => 'rgba(4,5,10,0.7)',
            'footerBg' => '#02030a',
            'scheme' => 'dark',
        ],
    ],

    'nova' => [
        'name' => 'Nova',
        'description' => 'Light, clean, corporate-credible. White canvas, big type, brand-blue accent. Wave-Access energy, AKH polish.',
        'hero_variant' => 'nova',
        'layout_variant' => 'split',
        'uses_three' => false,
        'is_premium' => false,
        'tokens' => [
            'bg' => '#ffffff',
            'bg2' => '#f6f8fc',
            'surface' => '#ffffff',
            'surface2' => '#f2f5fb',
            'glass' => 'rgba(255,255,255,0.7)',
            'glassBorder' => 'rgba(12,16,30,0.08)',
            'hairline' => 'rgba(12,16,30,0.09)',
            'text' => '#0b0d14',
            'textSecondary' => '#454c5e',
            'textMuted' => '#737b8c',
            'primary' => '#3b5cf6',
            'primaryHover' => '#2f4ce0',
            'onPrimary' => '#ffffff',
            'gradFrom' => '#1fa8e8',
            'gradVia' => '#3b5cf6',
            'gradTo' => '#7c3aed',
            'ring' => 'rgba(59,92,246,0.4)',
            'glow' => 'rgba(59,92,246,0.18)',
            'fontDisplay' => "'Plus Jakarta Sans'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '14px',
            'navBg' => 'rgba(255,255,255,0.8)',
            'footerBg' => '#0b0d14',
            'scheme' => 'light',
        ],
    ],

    'vertex' => [
        'name' => 'Vertex',
        'description' => 'Bold editorial flex. Oversized typography, high contrast, understated-metric energy. Metric.am attitude.',
        'hero_variant' => 'vertex',
        'layout_variant' => 'editorial',
        'uses_three' => false,
        'is_premium' => false,
        'tokens' => [
            'bg' => '#0d0d0f',
            'bg2' => '#121214',
            'surface' => '#161618',
            'surface2' => '#1d1d20',
            'glass' => 'rgba(28,28,32,0.55)',
            'glassBorder' => 'rgba(255,255,255,0.1)',
            'hairline' => 'rgba(255,255,255,0.1)',
            'text' => '#fafafa',
            'textSecondary' => '#b8b8be',
            'textMuted' => '#7e7e86',
            'primary' => '#c8ff3d',
            'primaryHover' => '#d6ff6b',
            'onPrimary' => '#0d0d0f',
            'gradFrom' => '#28baf3',
            'gradVia' => '#7e2cfd',
            'gradTo' => '#c8ff3d',
            'ring' => 'rgba(200,255,61,0.45)',
            'glow' => 'rgba(200,255,61,0.25)',
            'fontDisplay' => "'Sora'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '8px',
            'navBg' => 'rgba(13,13,15,0.75)',
            'footerBg' => '#08080a',
            'scheme' => 'dark',
        ],
    ],

    'pulse' => [
        'name' => 'Pulse',
        'description' => 'Systems & product. Indigo-teal, structured grid, engineered calm. Huddle-style clarity for platform work.',
        'hero_variant' => 'pulse',
        'layout_variant' => 'systems',
        'uses_three' => false,
        'is_premium' => false,
        'tokens' => [
            'bg' => '#0a0f1a',
            'bg2' => '#0d1322',
            'surface' => '#111a2e',
            'surface2' => '#16213a',
            'glass' => 'rgba(17,26,46,0.6)',
            'glassBorder' => 'rgba(120,200,220,0.14)',
            'hairline' => 'rgba(140,180,220,0.1)',
            'text' => '#eef4fb',
            'textSecondary' => '#9fb0c6',
            'textMuted' => '#6b7c93',
            'primary' => '#2dd4bf',
            'primaryHover' => '#5ce0d0',
            'onPrimary' => '#04130f',
            'gradFrom' => '#2dd4bf',
            'gradVia' => '#3b82f6',
            'gradTo' => '#6366f1',
            'ring' => 'rgba(45,212,191,0.45)',
            'glow' => 'rgba(45,212,191,0.28)',
            'fontDisplay' => "'Outfit'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '12px',
            'navBg' => 'rgba(10,15,26,0.74)',
            'footerBg' => '#070b14',
            'scheme' => 'dark',
        ],
    ],

    'monolith' => [
        'name' => 'Monolith',
        'description' => 'Ultra-minimal monochrome with a single electric accent. Maximum restraint, maximum confidence.',
        'hero_variant' => 'minimal',
        'layout_variant' => 'standard',
        'uses_three' => false,
        'is_premium' => false,
        'tokens' => [
            'bg' => '#0a0a0a',
            'bg2' => '#0f0f0f',
            'surface' => '#141414',
            'surface2' => '#1c1c1c',
            'glass' => 'rgba(20,20,20,0.6)',
            'glassBorder' => 'rgba(255,255,255,0.12)',
            'hairline' => 'rgba(255,255,255,0.1)',
            'text' => '#fafafa',
            'textSecondary' => '#a3a3a3',
            'textMuted' => '#6f6f6f',
            'primary' => '#5778f8',
            'primaryHover' => '#7a95ff',
            'onPrimary' => '#ffffff',
            'gradFrom' => '#5778f8',
            'gradVia' => '#5778f8',
            'gradTo' => '#5778f8',
            'ring' => 'rgba(87,120,248,0.5)',
            'glow' => 'rgba(87,120,248,0.25)',
            'fontDisplay' => "'Inter'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '10px',
            'navBg' => 'rgba(10,10,10,0.75)',
            'footerBg' => '#060606',
            'scheme' => 'dark',
        ],
    ],

    'flux' => [
        'name' => 'Flux',
        'description' => 'Liquid WebGL gradient in motion. Three.js animated mesh, vivid AKH spectrum, hypnotic and alive.',
        'hero_variant' => 'flux',
        'layout_variant' => 'standard',
        'uses_three' => true,
        'is_premium' => true,
        'tokens' => [
            'bg' => '#070611',
            'bg2' => '#0b0918',
            'surface' => '#110e22',
            'surface2' => '#17132e',
            'glass' => 'rgba(20,16,40,0.5)',
            'glassBorder' => 'rgba(168,85,247,0.18)',
            'hairline' => 'rgba(180,140,255,0.12)',
            'text' => '#f4f0ff',
            'textSecondary' => '#bcaee0',
            'textMuted' => '#7c719c',
            'primary' => '#a855f7',
            'primaryHover' => '#c07bff',
            'onPrimary' => '#ffffff',
            'gradFrom' => '#22d3ee',
            'gradVia' => '#6366f1',
            'gradTo' => '#ec4899',
            'ring' => 'rgba(168,85,247,0.5)',
            'glow' => 'rgba(168,85,247,0.35)',
            'fontDisplay' => "'Space Grotesk'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '18px',
            'navBg' => 'rgba(7,6,17,0.7)',
            'footerBg' => '#040310',
            'scheme' => 'dark',
        ],
    ],

    'horizon' => [
        'name' => 'Horizon',
        'description' => 'Synthwave skyline. Live Three.js infinite neon perspective grid racing to a glowing horizon. Retro-future, electric, unforgettable.',
        'hero_variant' => 'grid',
        'layout_variant' => 'standard',
        'uses_three' => true,
        'is_premium' => true,
        'tokens' => [
            'bg' => '#07060f',
            'bg2' => '#0c0a1a',
            'surface' => '#130f26',
            'surface2' => '#1b1538',
            'glass' => 'rgba(27,21,56,0.5)',
            'glassBorder' => 'rgba(255,46,154,0.18)',
            'hairline' => 'rgba(177,75,255,0.14)',
            'text' => '#f6f0ff',
            'textSecondary' => '#c4b3e6',
            'textMuted' => '#8275a6',
            'primary' => '#ff2e9a',
            'primaryHover' => '#ff5fb1',
            'onPrimary' => '#ffffff',
            'gradFrom' => '#00e5ff',
            'gradVia' => '#b14bff',
            'gradTo' => '#ff2e9a',
            'ring' => 'rgba(255,46,154,0.5)',
            'glow' => 'rgba(177,75,255,0.35)',
            'fontDisplay' => "'Sora'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '12px',
            'navBg' => 'rgba(7,6,15,0.72)',
            'footerBg' => '#050409',
            'scheme' => 'dark',
        ],
    ],

    'singularity' => [
        'name' => 'Singularity',
        'description' => 'Event horizon. A Three.js wormhole tunnel falling toward a glowing accretion core. Awe-inspiring deep-space gravity.',
        'hero_variant' => 'singularity',
        'layout_variant' => 'standard',
        'uses_three' => true,
        'is_premium' => true,
        'tokens' => [
            'bg' => '#010207',
            'bg2' => '#04060f',
            'surface' => '#080d1a',
            'surface2' => '#0e1426',
            'glass' => 'rgba(14,20,38,0.52)',
            'glassBorder' => 'rgba(255,122,77,0.18)',
            'hairline' => 'rgba(255,150,90,0.12)',
            'text' => '#fdf3ec',
            'textSecondary' => '#c7b6ad',
            'textMuted' => '#857469',
            'primary' => '#ff7a4d',
            'primaryHover' => '#ff9670',
            'onPrimary' => '#1a0a04',
            'gradFrom' => '#ffd27a',
            'gradVia' => '#ff7a4d',
            'gradTo' => '#b15bff',
            'ring' => 'rgba(255,122,77,0.5)',
            'glow' => 'rgba(255,122,77,0.34)',
            'fontDisplay' => "'Space Grotesk'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '14px',
            'navBg' => 'rgba(1,2,7,0.72)',
            'footerBg' => '#010104',
            'scheme' => 'dark',
        ],
    ],

    'helix' => [
        'name' => 'Helix',
        'description' => 'Bio-tech elegance. A glowing Three.js DNA double-helix of particles rotating through infinite space. Living, precise, futuristic.',
        'hero_variant' => 'helix',
        'layout_variant' => 'standard',
        'uses_three' => true,
        'is_premium' => true,
        'tokens' => [
            'bg' => '#040a0a',
            'bg2' => '#061412',
            'surface' => '#0a1c1a',
            'surface2' => '#0f2624',
            'glass' => 'rgba(15,38,36,0.5)',
            'glassBorder' => 'rgba(47,245,200,0.18)',
            'hairline' => 'rgba(80,220,200,0.12)',
            'text' => '#eafff8',
            'textSecondary' => '#a3d8cd',
            'textMuted' => '#6a8c84',
            'primary' => '#2ff5c8',
            'primaryHover' => '#5ff8d6',
            'onPrimary' => '#02120e',
            'gradFrom' => '#34f5a0',
            'gradVia' => '#2fd0f5',
            'gradTo' => '#9b6bff',
            'ring' => 'rgba(47,245,200,0.46)',
            'glow' => 'rgba(47,245,200,0.3)',
            'fontDisplay' => "'Outfit'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '14px',
            'navBg' => 'rgba(4,10,10,0.72)',
            'footerBg' => '#020706',
            'scheme' => 'dark',
        ],
    ],

    'prism' => [
        'name' => 'Prism',
        'description' => 'Crystalline refraction. A faceted Three.js crystal turning in a field of orbiting glints, shimmering across the spectrum. High-end and mesmerising.',
        'hero_variant' => 'prism',
        'layout_variant' => 'standard',
        'uses_three' => true,
        'is_premium' => true,
        'tokens' => [
            'bg' => '#08070d',
            'bg2' => '#0d0b16',
            'surface' => '#14111f',
            'surface2' => '#1c1830',
            'glass' => 'rgba(28,24,48,0.5)',
            'glassBorder' => 'rgba(125,249,255,0.16)',
            'hairline' => 'rgba(192,139,255,0.12)',
            'text' => '#f5f2ff',
            'textSecondary' => '#bfb6d8',
            'textMuted' => '#7f7596',
            'primary' => '#7df9ff',
            'primaryHover' => '#a6fbff',
            'onPrimary' => '#06121a',
            'gradFrom' => '#7df9ff',
            'gradVia' => '#c08bff',
            'gradTo' => '#ff8bd4',
            'ring' => 'rgba(125,249,255,0.46)',
            'glow' => 'rgba(192,139,255,0.32)',
            'fontDisplay' => "'Plus Jakarta Sans'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '16px',
            'navBg' => 'rgba(8,7,13,0.72)',
            'footerBg' => '#050409',
            'scheme' => 'dark',
        ],
    ],

    'cosmos' => [
        'name' => 'Cosmos',
        'description' => 'Deep-space wonder. A live Three.js parallax starfield drifting through glowing nebula clouds. Vast, serene, classic sci-fi.',
        'hero_variant' => 'cosmos',
        'layout_variant' => 'standard',
        'uses_three' => true,
        'is_premium' => true,
        'tokens' => [
            'bg' => '#030410',
            'bg2' => '#05071a',
            'surface' => '#0a0e26',
            'surface2' => '#111634',
            'glass' => 'rgba(16,22,52,0.5)',
            'glassBorder' => 'rgba(120,160,255,0.16)',
            'hairline' => 'rgba(130,150,255,0.12)',
            'text' => '#eef1ff',
            'textSecondary' => '#a9b3df',
            'textMuted' => '#6b7099',
            'primary' => '#6f8cff',
            'primaryHover' => '#92a9ff',
            'onPrimary' => '#040616',
            'gradFrom' => '#3bd6ff',
            'gradVia' => '#6f8cff',
            'gradTo' => '#c46bff',
            'ring' => 'rgba(111,140,255,0.5)',
            'glow' => 'rgba(120,160,255,0.32)',
            'fontDisplay' => "'Space Grotesk'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '16px',
            'navBg' => 'rgba(3,4,16,0.72)',
            'footerBg' => '#02030c',
            'scheme' => 'dark',
        ],
    ],

    'stargate' => [
        'name' => 'Stargate',
        'description' => 'A mythic gateway. A rotating Three.js portal ring with a swirling event-horizon vortex. Cinematic and otherworldly.',
        'hero_variant' => 'stargate',
        'layout_variant' => 'standard',
        'uses_three' => true,
        'is_premium' => true,
        'tokens' => [
            'bg' => '#04080a',
            'bg2' => '#061014',
            'surface' => '#0a1a1f',
            'surface2' => '#0f2630',
            'glass' => 'rgba(15,38,48,0.5)',
            'glassBorder' => 'rgba(64,224,208,0.18)',
            'hairline' => 'rgba(90,210,200,0.12)',
            'text' => '#eafdff',
            'textSecondary' => '#a3cdd4',
            'textMuted' => '#6a8d94',
            'primary' => '#2fe0d0',
            'primaryHover' => '#5cf0e3',
            'onPrimary' => '#02130f',
            'gradFrom' => '#23e0c8',
            'gradVia' => '#36b6ff',
            'gradTo' => '#8a7bff',
            'ring' => 'rgba(47,224,208,0.5)',
            'glow' => 'rgba(54,182,255,0.3)',
            'fontDisplay' => "'Sora'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '14px',
            'navBg' => 'rgba(4,8,10,0.72)',
            'footerBg' => '#020708',
            'scheme' => 'dark',
        ],
    ],

    'brutalist' => [
        'name' => 'Brutalist',
        'description' => 'Tactile brutalism - paper-white canvas, monospace headlines, hard single-pixel edges, one electric accent. The 2026 anti-design statement.',
        'hero_variant' => 'minimal',
        'layout_variant' => 'editorial',
        'uses_three' => false,
        'is_premium' => false,
        'tokens' => [
            'bg' => '#f4f4ef',
            'bg2' => '#ebebe4',
            'surface' => '#ffffff',
            'surface2' => '#f4f4ef',
            'glass' => 'rgba(255,255,255,0.9)',
            'glassBorder' => 'rgba(10,10,10,0.9)',
            'hairline' => 'rgba(10,10,10,0.22)',
            'text' => '#0a0a0a',
            'textSecondary' => '#2e2e2e',
            'textMuted' => '#5c5c5c',
            'primary' => '#ff3d00',
            'primaryHover' => '#e02f00',
            'onPrimary' => '#ffffff',
            'gradFrom' => '#ff3d00',
            'gradVia' => '#ff3d00',
            'gradTo' => '#ff3d00',
            'ring' => 'rgba(255,61,0,0.5)',
            'glow' => 'rgba(255,61,0,0.18)',
            'fontDisplay' => "'JetBrains Mono'",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '0px',
            'navBg' => 'rgba(244,244,239,0.86)',
            'footerBg' => '#0a0a0a',
            'scheme' => 'light',
        ],
    ],

    'classic' => [
        'name' => 'Classic',
        'description' => 'Timeless and editorial. Warm off-white canvas, refined serif headlines, restrained ink-blue accent. No 3D - pure typographic craft.',
        'hero_variant' => 'minimal',
        'layout_variant' => 'editorial',
        'uses_three' => false,
        'is_premium' => false,
        'tokens' => [
            'bg' => '#fbfaf7',
            'bg2' => '#f3f1ea',
            'surface' => '#ffffff',
            'surface2' => '#f4f2ec',
            'glass' => 'rgba(255,255,255,0.72)',
            'glassBorder' => 'rgba(26,32,44,0.1)',
            'hairline' => 'rgba(26,32,44,0.12)',
            'text' => '#1a2233',
            'textSecondary' => '#475061',
            'textMuted' => '#6b7280',
            'primary' => '#1e3a8a',
            'primaryHover' => '#1d4ed8',
            'onPrimary' => '#ffffff',
            'gradFrom' => '#1e3a8a',
            'gradVia' => '#4338ca',
            'gradTo' => '#9333ea',
            'ring' => 'rgba(30,58,138,0.35)',
            'glow' => 'rgba(30,58,138,0.14)',
            'fontDisplay' => "'Fraunces', Georgia, serif",
            'fontBody' => "'Inter'",
            'fontMono' => "'JetBrains Mono'",
            'radius' => '6px',
            'navBg' => 'rgba(251,250,247,0.82)',
            'footerBg' => '#1a2233',
            'scheme' => 'light',
        ],
    ],

];
